# -*- coding: utf-8 -*-
"""Diamonds_quality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRQ3lyCkSnE9gWYLIHiNEjH9KmhzKxT5
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('Diamonds_Quality.csv')
x = dataset.iloc[: , : -1]
y = dataset.iloc[: , -1]
print(x)
print(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, 
test_size=0.25, random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

for coln in dataset:
  dataset[coln]=dataset[coln].astype('category').cat.codes

from sklearn.tree import DecisionTreeClassifier
classifier =  DecisionTreeClassifier(criterion='entropy' , random_state =0)
classifier.fit(x_train , y_train)

y_pred=classifier.predict(x_test)
plt.plot(y_pred)
plt.show

from sklearn.metrics import confusion_matrix
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
plt.plot(cm)
plt.show

from sklearn.tree import export_graphviz
import graphviz 
graphviz.Source(export_graphviz(classifier,feature_names=x.columns, filled=True, class_names=['1','2','3','4','5','6','7'], out_file=None))